spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
server:
  port: 18082
  cloud:
    nacos:
      server-addr: 192.168.2.13:8848
feign:
  hystrix:
    enabled: true
pic:
  url: http://192.168.211.132:8080