spring:
  application:
    name: gateway-web
  redis:
    host: 192.168.211.132
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*" # 支持所有的请求头给服务端
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: host_route
          uri: lb://goods
          predicates:
            #  - Host=www.baidu.com* # http://cloud.itheima.com:8001/brand --->http://localhost:18081/brand
            #  - Path=/brand/** # http://localhost:8001/brand --->http://localhost:18081/brand
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
            #  - PrefixPath=/brand # 当请求来的时候：http://localhost:8001/1115 -->http://localhost:18081/brand/1115
            - StripPrefix=1 # 当请求来的时候：http://localhost:8001/api/brand/1115 -->http://localhost:18081/brand/1115 去掉一个前缀。
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        #用户微服务 shift + tab
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
server:
  port: 8001
  cloud:
    nacos:
      server-addr: 192.168.2.13:8848
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true