server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.211.132
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  cloud:
    nacos:
      server-addr: 192.168.254.1:8848
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
jks:
  name: changgou.jks
  storepassword: changgou
  keypassword: changgou
  alias: changgou


